USE [master]
GO

/****** Object:  Database [AzureDB]    Script Date: 4/1/2021 12:15:51 PM ******/
CREATE DATABASE [AzureDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AzureDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AzureDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AzureDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AzureDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AzureDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AzureDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AzureDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AzureDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AzureDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AzureDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AzureDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AzureDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AzureDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AzureDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AzureDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AzureDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AzureDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AzureDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AzureDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AzureDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AzureDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AzureDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AzureDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AzureDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AzureDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AzureDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AzureDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AzureDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AzureDB] SET  MULTI_USER 
GO

ALTER DATABASE [AzureDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AzureDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AzureDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AzureDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AzureDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AzureDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AzureDB] SET  READ_WRITE 
GO

